variable "project" { type = string }
variable "environment" { type = string }
variable "public_subnet_id" { type = string }
variable "ec2_security_group_id" { type = string }
variable "sns_topic_arn" { type = string }
variable "audit_bucket_arn" { type = string }
variable "ssm_prefix" { type = string }

variable "db_username" {
  description = "PostgreSQL master username"
  type        = string
  default     = "finflow"
}

variable "db_password" {
  description = "PostgreSQL and Redis password — generated by the secrets module"
  type        = string
  sensitive   = true
}

variable "db_name" {
  description = "PostgreSQL database name"
  type        = string
  default     = "finflow_db"
}

variable "key_public" {
  description = "SSH public key content for EC2 access"
  type        = string
}
